apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gke
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-gke
  template:
    metadata:
      labels:
        app: hello-gke
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always