apiVersion: v1
kind: Service
metadata:
  name: hello-gke
spec:
  selector:
    app: hello-gke
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8081
      protocol: TCP
      name: https