name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: hello-gke
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: hello-gke
  IMAGE: hello-gke-image
  TAG: 1.0.0

jobs:
  build:  
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace}}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Cache executable JAR
        uses: actions/upload-artifact@v3
        with:
          name: executable-JAR
          path: target/hello-gke-0.0.1-SNAPSHOT.jar
  
  test:  
    name: Test
    runs-on: ubuntu-latest
    needs: [build]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PMD Source Code Analyzer
        uses: sfdx-actions/setup-pmd@v1
    
      - name: Run PMD Source Code Analyzer
        run: pmd -d ./src -R pmd_ruleset.xml -f text

  deploy:  
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test]

    steps:

      - name: Download cached executable JAR
        uses: actions/download-artifact@v3
        with:
          name: executable-JAR
          path: target/hello-gke-0.0.1-SNAPSHOT.jar

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace}}

      - name: Setup Google Cloud CLI (gcloud)
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_SA_KEY}}
          project_id: ${{secrets.GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .

      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide